level: info
ignore_system_index: true
elastics:
  es5:
    addresses:
      - "http://127.0.0.1:15200"
    user: ""
    password: ""

  es6:
    addresses:
      - "http://127.0.0.1:16200"
    user: ""
    password: ""

  es7:
    addresses:
      - "http://127.0.0.1:17200"
    user: ""
    password: ""

  es8:
    addresses:
      - "http://127.0.0.1:18200"
    user: ""
    password: ""

tasks:
#  - name: sync_task
#    source_es: es5
#    target_es: es8
#    index_pattern: ".*"
#    action: compare
#    force: true
#
#  - name: compare_task
#    source_es: es5
#    target_es: es8
#    index_pattern: ".*"
#    action: compare

#  - name: export_task
#    source_es: es5
#    action: export
#    index_file_root: "C:/Users/andy/Documents"
#    index_file_pairs:
#      -
#        index: "sample_hello"
#        index_file_dir: "C:/Users/andy/Documents/abc"
#
#    action_parallelism: 2
#
#  - name: import_task
#    target_es: es8
#    action: import
#    index_file_pairs:
#      -
#        index: "sample_hello3"
#        index_file_dir: "C:/Users/andy/Documents/abc"
#    force: true
#    action_parallelism: 1
#    slice_size: 1

#  - name: compare_task
#    source_es: es5
#    target_es: es8
#    action: compare
#    index_pairs:
#      -
#        source_index: "sample_hello"
#        target_index: "sample_hello3"
#
#    action_parallelism: 2
#    slice_size: 1

  - name: sync
    source_es: es5
    target_es: es8
    action: sync
    index_pattern: .*
    index_pairs:
      -
        source_index: "sample_index"
        target_index: "sample_hello31"

    scroll_size: 201
    slice_size: 202
    scroll_time: 203
    parallelism: 204
    buffer_count: 205
    action_parallelism: 206
    action_size: 207
    ids:
      - "1"
      - "2"
      - "3"

    force: true

#  - name: sync-diff
#    source_es: es5
#    target_es: es8
#    action: sync_diff
#    index_pairs:
#      -
#        source_index: "sample_index"
#        target_index: "sample_hello31"
#
#    action_parallelism: 2
#    slice_size: 2

#  - name: compare
#    source_es: es5
#    target_es: es8
#    action: compare
#    index_pairs:
#      -
#        source_index: "sample_index"
#        target_index: "sample_hello31"
#
#    action_parallelism: 2
#    slice_size: 2

#  - name: compare
#    source_es: es5
#    target_es: es8
#    action: compare
#    index_pairs:
#      -
#        source_index: "sample_index"
#        target_index: "sample_hello31"
#
#    action_parallelism: 2
#    slice_size: 2

#  - name: task2
#    source_es: es5
#    target_es: es8
#    #    index_pairs:
#    #      -
#    #        source_index: "sample_hello"
#    #        target_index: "sample_hello"
#    index_pattern: "sample*"
#    action: compare
#  - name: task3
#    source_es: es5
#    target_es: es8
#    buffer_count: 1000
#    slice_size: 5
#
#    #    index_pairs:
#    #      -
#    #        source_index: "sample_hello"
#    #        target_index: "sample_hello"
#    index_pattern: "sample*"
#    action: sync_diff
#    action: sync_diff

gateway:
  gateway_address: "0.0.0.0:8080"
  gateway_user: "user",
  gateway_password: "12342",

  source_es: es5
  target_es: es8
  master: es5
